### ISSUE TITLE
价格为0时，不要显示购买和试课按钮，直接显示查看

### ISSUE THREAD

**Issue by Calvin-he** [Calvin-he/cognitive_english#1]
价格为0时，不要显示购买和试课按钮，直接显示查看

**Comment by honey058** [comment]
（以后支付做好后，还要做一个链接，就是学员如果填写了基本信息且转发了朋友圈，就免费，不然就要收费）

**Comment by Calvin-he** [comment]
solved

**Comment by Calvin-he** [comment]
>  还要做一个链接，就是学员如果填写了基本信息且转发了朋友圈，就免费，不然就要收费 

@honey058 Please submit it as a new feature.

**Comment by honey058** [comment]
那是不是就可以上线了？周末抽个时间聊聊？
