### ISSUE TITLE
急~ 编辑页面无法提交

### ISSUE THREAD

**Issue by honey058** [Calvin-he/cognitive_english#14]
<img width="1280" alt="screen shot 2017-08-05 at 9 55 54 am" src="https://user-images.githubusercontent.com/19848131/28992014-5f541948-79c4-11e7-9f0c-b92e8361483a.png">
这个无法提交，我编辑的内容都更新不了。。。

**Comment by honey058** [comment]
图片也无法更新

**Comment by Calvin-he** [comment]
solved
