### ISSUE TITLE
这张图片的最上面这栏去掉

### ISSUE THREAD

**Issue by honey058** [Calvin-he/cognitive_english#15]
我发现，这个课程名这栏，COCO进阶（III），在这页的时候可以去掉。一来信息冗余，二来，这是更重要的，在图片的上方，很容易和图片配色发生冲突，界面不好看。

![wechatimg12](https://user-images.githubusercontent.com/19848131/28994131-4f824442-79f9-11e7-8a92-cb1fedb5ea6d.png)

**Comment by Calvin-he** [comment]
solved
