### ISSUE TITLE
分享转发时，不要显示网络链接

### ISSUE THREAD

**Issue by honey058** [Calvin-he/cognitive_english#25]
这是微店转发链接的样式：
![Uploading WechatIMG16.jpeg…]()

这是我们自己的

![Uploading WechatIMG15.jpeg…]()

我想的是，网络链接变为：认知英语教学

上面的内容，就和分享的具体内容一致。比如，如果是整个课程，就写：我发现了一个学英语的科学产品；如果是单个课程，就和标题一致。

**Comment by Calvin-he** [comment]
solved
