### ISSUE TITLE
收费逻辑

### ISSUE THREAD

**Issue by honey058** [Calvin-he/cognitive_english#32]
糖果的收费逻辑是这样的：

对赌收费，先收100元，如果你哪一天忘记打卡了，就收钱，一天一元。

我们在内容上，设置成一天只能学习一天的内容，第二天的是要在当天零点以后才可以打开。

如果第二天忘了继续学了，那么第三天也只能打开第二天的。

这样，一个100天的学习内容，比如有人每天都按时打卡，最后就不收钱了。如果一人要花110天，那么最后要扣掉10元，返给他的就只有90元了。

我想了下，这样才最能驱动学员每天学习。至于退费怎么退，如果先技术上不能实现，就先人工退费。刚开始人不会太多。

你看下，这个逻辑，在技术上怎么实现

**Comment by Calvin-he** [comment]
@honey058  添加到Wiki中了： [收费逻辑](https://github.com/Calvin-he/cogen/wiki/%E6%94%B6%E8%B4%B9%E9%80%BB%E8%BE%91)
